language: scala
scala:
    - 2.10.6
    - 2.11.8
jdk:
    - oraclejdk8
    - oraclejdk7
    - openjdk7
env:
    global:
        - SCALATEST_SPAN_SCALE_FACTOR=10
        - EXTRA_SBT_OPT="-J-XX:ReservedCodeCacheSize=256M -Dsun.io.serialization.extendedDebugInfo=true"
    # Split build between unit and integration tests
    matrix:
        - TEST_SUITE=test
        - TEST_SUITE=it:test
script:
    # Run our test for a specific Scala version and specific test suite
    - sbt ++$TRAVIS_SCALA_VERSION $EXTRA_SBT_OPT "$TEST_SUITE"

    # Avoid unnecessary cache updates
    - find $HOME/.sbt -name "*.lock" | xargs rm
    - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
sudo: false
cache:
    directories:
        - $HOME/.ivy2/cache
        - $HOME/.coursier/cache/v1
        - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
        - $HOME/.sbt/launchers/0.13.11
notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/7a65e32f729a0a29267e
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: false     # default: false

